<?php
// =============================================================================
// setup_worker.php — Worker installation after the first-run wizard
// =============================================================================
// Endpoint accessible only within 10 minutes after a successsful
// installation, protected by a one-time session token.
// =============================================================================
define('FULGURITE_SETUP', true);

// Full bootstrap (DB exists after finalize)
require_once __DIR__ . '/../src/bootstrap.php';

header('Content-Type: application/json; charset=utf-8');
header('X-Content-Type-Options: nosniff');

// ── Guard 1: installation must be completed ───────────────────────────────────
$installedFile = dirname(__DIR__) . '/data/.installed';
if (!is_file($installedFile)) {
    http_response_code(403);
    echo json_encode(['ok' => false, 'message' => 'Installation non terminée.']);
    exit;
}

// ── Guard 2: one-time session token generated by setup_action.php/finalize ──
$sessionToken  = $_SESSION['setup_worker_token'] ?? '';
$tokenExpires  = (int) ($_SESSION['setup_worker_token_expires'] ?? 0);
$requestToken  = trim((string) ($_POST['setup_token'] ?? ''));

if ($sessionToken === '' || $requestToken === '' || $requestToken !== $sessionToken) {
    http_response_code(403);
    echo json_encode(['ok' => false, 'message' => 'Token invalide ou absent.']);
    exit;
}

if (time() > $tokenExpires) {
    unset($_SESSION['setup_worker_token'], $_SESSION['setup_worker_token_expires']);
    http_response_code(403);
    echo json_encode(['ok' => false, 'message' => 'Token expiré. Reconnectez-vous à l\'interface pour configurer le worker.']);
    exit;
}

// ── Dispatcher ────────────────────────────────────────────────────────────────
$action       = trim((string) ($_POST['action'] ?? ''));
$workerName   = AppConfig::workerDefaultName();
$limit        = AppConfig::workerLimit();
$staleMinutes = AppConfig::workerStaleMinutes();

try {
    $response = match ($action) {
        'install_cron' => (static function () use ($workerName, $limit, $staleMinutes): array {
            $res = WorkerManager::installCron($workerName, $limit, $staleMinutes);
            return array_merge(['ok' => !empty($res['success'])], $res);
        })(),

        'generate_systemd_unit' => (static function () use ($workerName): array {
            $res = WorkerManager::generateSystemdUnit($workerName);
            return array_merge(['ok' => !empty($res['success'])], $res);
        })(),

        'check_auto_install' => (static function (): array {
            $check = WorkerManager::canAutoInstallSystemd();
            return [
                'ok'     => true,
                'can'    => $check['can'],
                'reason' => $check['reason'],
                'helper' => $check['helper'] ?? '',
            ];
        })(),

        'install_systemd' => (static function () use ($workerName): array {
            $res = WorkerManager::installSystemd($workerName);
            return array_merge(['ok' => !empty($res['success'])], $res);
        })(),

        default => null,
    };

    if ($response === null) {
        http_response_code(400);
        echo json_encode(['ok' => false, 'message' => 'Action inconnue.']);
        exit;
    }

    echo json_encode($response);

} catch (Throwable $e) {
    http_response_code(500);
    echo json_encode(['ok' => false, 'message' => 'Erreur interne : ' . $e->getMessage()]);
}
