<?php
return [
    ['iso2' => 'AF', 'extension' => '93'],
    ['iso2' => 'AL', 'extension' => '355'],
    ['iso2' => 'DZ', 'extension' => '213'],
    ['iso2' => 'AD', 'extension' => '376'],
    ['iso2' => 'AO', 'extension' => '244'],
    ['iso2' => 'AR', 'extension' => '54'],
    ['iso2' => 'AM', 'extension' => '374'],
    ['iso2' => 'AU', 'extension' => '61'],
    ['iso2' => 'AT', 'extension' => '43'],
    ['iso2' => 'BE', 'extension' => '32'],
    ['iso2' => 'BR', 'extension' => '55'],
    ['iso2' => 'CA', 'extension' => '1'],
    ['iso2' => 'CH', 'extension' => '41'],
    ['iso2' => 'DE', 'extension' => '49'],
    ['iso2' => 'ES', 'extension' => '34'],
    ['iso2' => 'FR', 'extension' => '33'],
    ['iso2' => 'GB', 'extension' => '44'],
    ['iso2' => 'IT', 'extension' => '39'],
    ['iso2' => 'LU', 'extension' => '352'],
    ['iso2' => 'MA', 'extension' => '212'],
    ['iso2' => 'NL', 'extension' => '31'],
    ['iso2' => 'PT', 'extension' => '351'],
    ['iso2' => 'US', 'extension' => '1'],
];
