<?php

return [
    'max_bytes' => 16384,
    'max_lines' => 64,
    'max_name_length' => 120,
    'allowed_scopes' => ['local', 'remote', 'both'],
    'autocomplete_values' => [
        'systemctl_actions' => ['reload', 'restart', 'start', 'stop', 'status'],
        'systemd_units' => ['nginx.service', 'apache2.service', 'php8.2-fpm.service', 'mysql.service', 'postgresql.service'],
        'fsfreeze_actions' => ['--freeze', '--unfreeze'],
        'mount_points' => ['{{SOURCE_PATH_1}}', '{{SOURCE_PATH_2}}', '/srv/data', '/var/lib/mysql', '/var/www'],
        'sleep_durations' => ['1', '2', '5', '10', '15', '30', '60'],
    ],
    'variables' => [
        'APP_NAME' => [
            'label' => 'Application',
            'category' => 'Application',
            'description' => 'Nom court de l application.',
            'type' => 'string',
            'sample' => 'fulgurite',
        ],
        'SCRIPT_NAME' => [
            'label' => 'Nom du script',
            'category' => 'Script',
            'description' => 'Nom du script approuve actuellement execute.',
            'type' => 'string',
            'sample' => 'freeze-volume',
        ],
        'JOB_ID' => [
            'label' => 'ID du job',
            'category' => 'Job',
            'description' => 'Identifiant numerique du job de sauvegarde.',
            'type' => 'integer',
            'sample' => '42',
        ],
        'JOB_NAME' => [
            'label' => 'Nom du job',
            'category' => 'Job',
            'description' => 'Nom du job de sauvegarde.',
            'type' => 'string',
            'sample' => 'backup-prod',
        ],
        'JOB_DESCRIPTION' => [
            'label' => 'Description du job',
            'category' => 'Job',
            'description' => 'Description libre du job.',
            'type' => 'string',
            'sample' => 'Sauvegarde quotidienne',
        ],
        'EXECUTION_SCOPE' => [
            'label' => 'Mode d execution',
            'category' => 'Execution',
            'description' => 'Mode local ou distant du job courant.',
            'type' => 'string',
            'sample' => 'local',
        ],
        'CURRENT_DATE' => [
            'label' => 'Date courante',
            'category' => 'Execution',
            'description' => 'Date ISO de l execution.',
            'type' => 'string',
            'sample' => '2026-04-10',
        ],
        'CURRENT_TIME' => [
            'label' => 'Heure courante',
            'category' => 'Execution',
            'description' => 'Heure courante de l execution.',
            'type' => 'string',
            'sample' => '14:30:00',
        ],
        'CURRENT_DATETIME' => [
            'label' => 'Date et heure',
            'category' => 'Execution',
            'description' => 'Horodatage complet ISO 8601.',
            'type' => 'string',
            'sample' => '2026-04-10T14:30:00+02:00',
        ],
        'REPO_ID' => [
            'label' => 'ID du depot',
            'category' => 'Depot',
            'description' => 'Identifiant du depot associe au job.',
            'type' => 'integer',
            'sample' => '8',
        ],
        'REPO_NAME' => [
            'label' => 'Nom du depot',
            'category' => 'Depot',
            'description' => 'Nom logique du depot dans Fulgurite.',
            'type' => 'string',
            'sample' => 'repo-production',
        ],
        'REPO_PATH' => [
            'label' => 'Chemin du depot',
            'category' => 'Depot',
            'description' => 'Chemin ou cible du depot principal.',
            'type' => 'path',
            'sample' => '/backups/restic/repo',
        ],
        'REMOTE_REPO_PATH' => [
            'label' => 'Chemin distant du depot',
            'category' => 'Depot',
            'description' => 'Chemin du depot vu depuis l hote distant, sinon chemin du depot.',
            'type' => 'path',
            'sample' => '/srv/backups/repo',
        ],
        'HOST_ID' => [
            'label' => 'ID de l hote',
            'category' => 'Hote',
            'description' => 'Identifiant de l hote cible si le job est distant.',
            'type' => 'integer',
            'sample' => '3',
        ],
        'HOST_NAME' => [
            'label' => 'Nom de l hote',
            'category' => 'Hote',
            'description' => 'Nom logique de l hote dans Fulgurite.',
            'type' => 'string',
            'sample' => 'vm-prod',
        ],
        'HOST_HOSTNAME' => [
            'label' => 'Hostname',
            'category' => 'Hote',
            'description' => 'Adresse ou hostname SSH de l hote.',
            'type' => 'string',
            'sample' => 'prod.example.internal',
        ],
        'HOST_USER' => [
            'label' => 'Utilisateur SSH',
            'category' => 'Hote',
            'description' => 'Utilisateur distant configure pour le job.',
            'type' => 'string',
            'sample' => 'backup',
        ],
        'HOST_PORT' => [
            'label' => 'Port SSH',
            'category' => 'Hote',
            'description' => 'Port SSH de l hote distant.',
            'type' => 'integer',
            'sample' => '22',
        ],
        'HOSTNAME_OVERRIDE' => [
            'label' => 'Nom d hote Restic',
            'category' => 'Hote',
            'description' => 'Valeur de host override envoyee a Restic.',
            'type' => 'string',
            'sample' => 'prod-app-01',
        ],
        'SOURCE_PATH_COUNT' => [
            'label' => 'Nombre de sources',
            'category' => 'Sources',
            'description' => 'Nombre de chemins sources du job.',
            'type' => 'integer',
            'sample' => '2',
        ],
        'SOURCE_PATH_1' => [
            'label' => 'Source 1',
            'category' => 'Sources',
            'description' => 'Premier chemin source du job.',
            'type' => 'path',
            'sample' => '/srv/data',
        ],
        'SOURCE_PATH_2' => [
            'label' => 'Source 2',
            'category' => 'Sources',
            'description' => 'Deuxieme chemin source du job.',
            'type' => 'path',
            'sample' => '/srv/www',
        ],
        'SOURCE_PATH_3' => [
            'label' => 'Source 3',
            'category' => 'Sources',
            'description' => 'Troisieme chemin source du job.',
            'type' => 'path',
            'sample' => '/srv/lib',
        ],
        'SOURCE_PATH_4' => [
            'label' => 'Source 4',
            'category' => 'Sources',
            'description' => 'Quatrieme chemin source du job.',
            'type' => 'path',
            'sample' => '/srv/cache',
        ],
        'SOURCE_PATH_5' => [
            'label' => 'Source 5',
            'category' => 'Sources',
            'description' => 'Cinquieme chemin source du job.',
            'type' => 'path',
            'sample' => '/srv/log',
        ],
    ],
    'banned_commands' => [
        'bash', 'sh', 'dash', 'zsh', 'ksh', 'fish',
        'python', 'python3', 'perl', 'php', 'ruby', 'node', 'npm', 'npx',
        'curl', 'wget', 'nc', 'ncat', 'netcat', 'socat', 'telnet',
        'ssh', 'sshpass', 'scp', 'sftp',
        'sudo', 'su', 'pkexec',
        'eval', 'exec', 'source', '.',
        'rm', 'mv', 'dd', 'mkfs', 'mount', 'umount',
        'chmod', 'chown', 'chgrp', 'setfacl',
        'docker', 'podman', 'kubectl',
    ],
    'banned_patterns' => [
        '/[;&|<>]/',
        '/`/',
        '/\$\(/',
        '/\$\{/',
        '/(^|[^\\\\])\$/',
        '/\b(?:for|while|until|case|then|do|done|function)\b/i',
    ],
    'allowed_commands' => [
        'systemctl' => [
            'binary' => '/bin/systemctl',
            'label' => 'systemctl',
            'description' => 'Controle de services systemd avec un sous-ensemble restreint.',
            'validator' => 'validateSystemctl',
            'allowed_scopes' => ['local', 'remote'],
            'autocomplete_insert' => 'systemctl ',
            'autocomplete_snippet' => 'systemctl reload nginx.service',
        ],
        'fsfreeze' => [
            'binary' => '/sbin/fsfreeze',
            'label' => 'fsfreeze',
            'description' => 'Gel / degel d un point de montage explicitement cible.',
            'validator' => 'validateFsfreeze',
            'allowed_scopes' => ['local', 'remote'],
            'autocomplete_insert' => 'fsfreeze ',
            'autocomplete_snippet' => 'fsfreeze --freeze {{SOURCE_PATH_1}}',
        ],
        'sleep' => [
            'binary' => '/bin/sleep',
            'label' => 'sleep',
            'description' => 'Pause courte pour coordination simple.',
            'validator' => 'validateSleep',
            'allowed_scopes' => ['local', 'remote'],
            'autocomplete_insert' => 'sleep ',
            'autocomplete_snippet' => 'sleep 2',
        ],
    ],
];
